// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaAcademicoAlunoMS.src.Data;

#nullable disable

namespace SistemaAcademicoAlunoMS.Migrations
{
    [DbContext(typeof(AlunoDbContext))]
    partial class AlunoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaAcademicoAlunoMS.src.Domain.Entities.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RA")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Alunos", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoAlunoMS.src.Domain.Entities.AlunoCursoDisciplina", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DataFim")
                        .HasColumnType("Date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("Date");

                    b.Property<decimal>("MediaFinal")
                        .HasColumnType("Decimal(10,2)");

                    b.Property<string>("NomeCurso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeDisciplina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiglaDisciplina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.HasKey("AlunoId", "DisciplinaId", "CursoId");

                    b.ToTable("Aluno_Curso_Discplina", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoAlunoMS.src.Domain.Entities.AlunoCursoDisciplinaNota", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("Bimestre")
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("Date");

                    b.Property<decimal>("Nota")
                        .HasColumnType("Decimal(10,2)");

                    b.Property<int>("Peso")
                        .HasColumnType("INT");

                    b.HasKey("AlunoId", "DisciplinaId", "CursoId", "Bimestre");

                    b.ToTable("Aluno_Curso_Discplina_Nota", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoAlunoMS.src.Domain.Entities.MatriculaAlunoCurso", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DataFim")
                        .HasColumnType("Date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("Date");

                    b.Property<string>("NomeCurso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("AlunoId", "CursoId");

                    b.ToTable("Matricula_Aluno_Curso", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoAlunoMS.src.Domain.Entities.AlunoCursoDisciplina", b =>
                {
                    b.HasOne("SistemaAcademicoAlunoMS.src.Domain.Entities.Aluno", "Aluno")
                        .WithMany("Disciplinas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("SistemaAcademicoAlunoMS.src.Domain.Entities.AlunoCursoDisciplinaNota", b =>
                {
                    b.HasOne("SistemaAcademicoAlunoMS.src.Domain.Entities.Aluno", "Aluno")
                        .WithMany("Notas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("SistemaAcademicoAlunoMS.src.Domain.Entities.MatriculaAlunoCurso", b =>
                {
                    b.HasOne("SistemaAcademicoAlunoMS.src.Domain.Entities.Aluno", "Aluno")
                        .WithMany("Matriculas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("SistemaAcademicoAlunoMS.src.Domain.Entities.Aluno", b =>
                {
                    b.Navigation("Disciplinas");

                    b.Navigation("Matriculas");

                    b.Navigation("Notas");
                });
#pragma warning restore 612, 618
        }
    }
}
