// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaAcademicoCursoMS.src.Data;

#nullable disable

namespace SistemaAcademicoCursoMS.Migrations
{
    [DbContext(typeof(CursoDbContext))]
    partial class CursoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DisciplinaFormacao", b =>
                {
                    b.Property<int>("DisciplinasId")
                        .HasColumnType("int");

                    b.Property<int>("FormacoesId")
                        .HasColumnType("int");

                    b.HasKey("DisciplinasId", "FormacoesId");

                    b.HasIndex("FormacoesId");

                    b.ToTable("DisciplinasFormacoes", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoCursoMS.src.Domain.Entities.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaConhecimento")
                        .HasMaxLength(100)
                        .HasColumnType("int")
                        .HasColumnName("Area_Conhecimento");

                    b.Property<string>("Descricao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cursos", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoCursoMS.src.Domain.Entities.CursoDisciplina", b =>
                {
                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<int>("CargaHoraria")
                        .HasMaxLength(100)
                        .HasColumnType("int")
                        .HasColumnName("Carga_Horaria");

                    b.Property<string>("Ementa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CursoId", "DisciplinaId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("Cursos_Disciplinas", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoCursoMS.src.Domain.Entities.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaConhecimento")
                        .HasMaxLength(100)
                        .HasColumnType("int")
                        .HasColumnName("Area_Conhecimento");

                    b.Property<string>("Codigo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sigla")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.ToTable("Disciplinas", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoCursoMS.src.Domain.Entities.Formacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaConhecimento")
                        .HasMaxLength(100)
                        .HasColumnType("int")
                        .HasColumnName("Area_Conhecimento");

                    b.Property<int>("Nivel")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Formacoes", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoCursoMS.src.Domain.Entities.GradeHoraria", b =>
                {
                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<int>("Dia")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Duracao")
                        .HasColumnType("time")
                        .HasColumnName("Duracao");

                    b.Property<TimeSpan>("HoraFim")
                        .HasColumnType("time")
                        .HasColumnName("Hora_Fim");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("Hora_Inicio");

                    b.HasKey("CursoId", "DisciplinaId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("Grade_Horaria", (string)null);
                });

            modelBuilder.Entity("DisciplinaFormacao", b =>
                {
                    b.HasOne("SistemaAcademicoCursoMS.src.Domain.Entities.Disciplina", null)
                        .WithMany()
                        .HasForeignKey("DisciplinasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAcademicoCursoMS.src.Domain.Entities.Formacao", null)
                        .WithMany()
                        .HasForeignKey("FormacoesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaAcademicoCursoMS.src.Domain.Entities.CursoDisciplina", b =>
                {
                    b.HasOne("SistemaAcademicoCursoMS.src.Domain.Entities.Curso", "Curso")
                        .WithMany("Disciplinas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaAcademicoCursoMS.src.Domain.Entities.Disciplina", "Disciplina")
                        .WithMany("Cursos")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("SistemaAcademicoCursoMS.src.Domain.Entities.GradeHoraria", b =>
                {
                    b.HasOne("SistemaAcademicoCursoMS.src.Domain.Entities.Curso", "Curso")
                        .WithMany("Horarios")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaAcademicoCursoMS.src.Domain.Entities.Disciplina", "Disciplina")
                        .WithMany("Horarios")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("SistemaAcademicoCursoMS.src.Domain.Entities.Curso", b =>
                {
                    b.Navigation("Disciplinas");

                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("SistemaAcademicoCursoMS.src.Domain.Entities.Disciplina", b =>
                {
                    b.Navigation("Cursos");

                    b.Navigation("Horarios");
                });
#pragma warning restore 612, 618
        }
    }
}
