FROM mcr.microsoft.com/dotnet/sdk:8.0 AS debug
WORKDIR /src

COPY ["SistemaAcademicoCursoMS.csproj", "./"]
RUN dotnet restore

COPY . .

# ENTRYPOINT de DEBUG: Usa 'dotnet watch run' para Hot Reload
ENTRYPOINT [ "dotnet", "watch", "--project", "SistemaAcademicoCursoMS.csproj", "run", "--urls", "http://+:8060" ]

# ====================================================================

# 2. Estágio de Publish (Alvo: publish)
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS publish
# ... (Inalterado)

# ====================================================================

# 3. Estágio de Release (Final) - Alvo: final
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app

COPY --from=publish /app/publish .
EXPOSE 8070
ENV ASPNETCORE_URLS=http://+:8060

# ENTRYPOINT de RELEASE: Execução rápida da DLL
ENTRYPOINT ["dotnet", "SistemaAcademicoCursoMS.dll"]