// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaAcademicoProfessorMS.src.Data;

#nullable disable

namespace SistemaAcademicoProfessorMS.Migrations
{
    [DbContext(typeof(ProfessorDbContext))]
    [Migration("20260115233130_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaAcademicoProfessorMS.src.Domain.Entities.AtribuicaoAula", b =>
                {
                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("Hora_Inicio");

                    b.Property<string>("Curso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dia")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("Disciplina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Duracao")
                        .HasColumnType("time")
                        .HasColumnName("Duracao");

                    b.Property<TimeSpan>("HoraFim")
                        .HasColumnType("time")
                        .HasColumnName("Hora_Fim");

                    b.HasKey("CursoId", "DisciplinaId", "ProfessorId", "HoraInicio");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Atribuicao_Aula", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoProfessorMS.src.Domain.Entities.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataContratacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Pontuacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,4)")
                        .HasDefaultValue(0m);

                    b.Property<string>("RegistroMec")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Professores", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoProfessorMS.src.Domain.Entities.ProfessorTitulo", b =>
                {
                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<int>("TitulosId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Inicio")
                        .HasColumnType("Date");

                    b.Property<DateOnly>("Termino")
                        .HasColumnType("Date");

                    b.HasKey("ProfessorId", "TitulosId");

                    b.HasIndex("TitulosId");

                    b.ToTable("Professores_Titulos", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoProfessorMS.src.Domain.Entities.Titulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaConhecimento")
                        .HasMaxLength(100)
                        .HasColumnType("int")
                        .HasColumnName("Area_Conhecimento");

                    b.Property<string>("Instituicao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Nivel")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ValorPontuacao")
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("Valor_Pontuacao");

                    b.HasKey("Id");

                    b.ToTable("Titulos", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoProfessorMS.src.Domain.Entities.AtribuicaoAula", b =>
                {
                    b.HasOne("SistemaAcademicoProfessorMS.src.Domain.Entities.Professor", "Professor")
                        .WithMany("Aulas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("SistemaAcademicoProfessorMS.src.Domain.Entities.ProfessorTitulo", b =>
                {
                    b.HasOne("SistemaAcademicoProfessorMS.src.Domain.Entities.Professor", "Professor")
                        .WithMany("Titulos")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaAcademicoProfessorMS.src.Domain.Entities.Titulo", "Titulo")
                        .WithMany("Professores")
                        .HasForeignKey("TitulosId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Professor");

                    b.Navigation("Titulo");
                });

            modelBuilder.Entity("SistemaAcademicoProfessorMS.src.Domain.Entities.Professor", b =>
                {
                    b.Navigation("Aulas");

                    b.Navigation("Titulos");
                });

            modelBuilder.Entity("SistemaAcademicoProfessorMS.src.Domain.Entities.Titulo", b =>
                {
                    b.Navigation("Professores");
                });
#pragma warning restore 612, 618
        }
    }
}
